### ISSUE TITLE
Execute qtv.cfg by default

### ISSUE THREAD

**Issue by niclaslindstedt** [deurk/qtv#1]
Currently you have to specify +exec qtv.cfg on cmdline for QTV to execute that file.

It should execute it by default.

**Comment by mushis** [comment]
this should be fairly easy to fix. has value

**Comment by meag** [comment]
@qqshka you've fixed this with https://github.com/deurk/qtv/commit/1ceda1dcf904ab2e7d458ec67f67f275c9b43742?

**Comment by qqshka** [comment]
@meag yes, if +exec is not specified on the cmd  line then exec qtv.cfg is executed by default, we could consider this as fix for this issue.
